'This is comment


'Mathematical operations
PRINT 1 + 1
PRINT 2 - 1
PRINT 2 * 2
PRINT 5 / 2: PRINT 5 \ 2
PRINT 3 ^ 2: PRINT 2 ^ 3

PRINT "3>2 "; 3 > 2: PRINT "3<2 "; 3 < 2
PRINT "3>3 "; 3 > 3: PRINT "3<3 "; 3 < 3
PRINT "3=3 "; 3 = 3 ' True equals -1, False equals 0


'Fractions
PRINT 3.1415

PRINT "1/2+1/4+1/4"; 1 / 2 + 1 / 4 + 1 / 4
PRINT "1/2+1/4+1/4"; 1 / 2 + 1 \ 4 + 1 \ 4


'Concat strings
PRINT "Hello" + " " + "World" + "!"


'Functions
PRINT ABS(45.5 - 100)
PRINT SGN(-5), SGN(0), SGN(5)

