I. 2 VAR AND 9 OPER
A := 1.27;
Y := (A*A + 2*A + 0.59)*(A*A + 2*A - 0.25);

II. 3 VAR AND 5 OPER
A := 1.27;
B := (A+2)*A;
Y := (B+0.59)*(B-0.25);

WRITE(Y);

WRITE(A);
WRITE(SUMMA);
WRITE(P1);

WRITE(A, A2, A3, A4);
WRITE(X, Y);

WRITE(1.5);
WRITE(X, Y);
WRITE(A+B/2, 3);
WRITE(X1, Y1, 1.5, Z);

X:= 0.5;
B:= 2.1;
C:= 6.2;
Y:= B*X + C;
WRITE(Y);

X:= 0.97;
X2:= X*X;
F:= (0.05*X2+0.39*X-0.08)*(0.05*X2-0.08);
WRITE(F);